---
- name: Deploy Flask application
  hosts: n1
  become: yes
  tasks:
    - name: install packages
      apt: name={{item}} state=present
      with_items:

      - python3-pip
      - python3-dev
      - nginx
      - libpq-dev
      - python3-venv
      - git

    - name: virtual enviroment
      command: python3 -m venv /opt/app/env 

    - name: we activate the environment
      command:  "source /opt/app/env/bin/activate"


    - name: Clone repository
      git:
        repo: https://github.com/Morjay007/Midclass-project.git
        dest: /opt/app
        clone: yes
      

    - name: install Flask application
      pip: 
        name: flask
        chdir: /opt/app/env/bin/pip
       
      
... 
