---
- name: Deploy Flask application
  hosts: n1
  become: yes
  tasks:
    - name: install packages
      apt: name={{item}} state=present
      with_items:

      - python3-pip
      - python3-dev
      - nginx
      - libpq-dev
      - python3-venv
      - git

    - name: virtual enviroment
      command: python3 -m venv /opt/app2.0/env 

    - name: we activate the environment
      command: /bin/bash -c "source /opt/app2.0/env/bin/activate"


    - name: Clone repository
      git:
        repo: https://github.com/Morjay007/Midclass-project.git
        dest: /opt/app2.0
        clone: no
        
    - name: copy flask app.py to app2.0 so it can be excuted
      copy:
        src: Flask_web_app.py
        dest: /opt/app2.0

    - name: install Flask application
      pip: 
        name: flask
        chdir: /opt/app2.0/env/bin/pip

    #- name: Change ssh port to 5000
     # ufw:
      #  rule: allow
       # proto: tcp 
       # port: 5000
      #become: yes
    - name: Change ssh port to 5000
      set_fact:
      ansible_port: 5000

    - name: restart ufw
      systemd:
        name: ufw
        state: restarted

       

    #- name: start flask
     # shell: "flask run"
      #environment:
       # FLASK_APP: /opt/app2.0/Flask_web_app.py

    - name: Install nodejs
      shell:  |
        curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
        sudo yum -y install nodejs
    - name: Install PM2
      shell: sudo npm install pm2@latest -g
    - name: check if flask app runs 
      shell: sudo netstat -tulnp | grep :5000
      register: flask_status  
    - name: start flask
      shell: sudo pm2 start app.py --interpreter python3
      failed_when: flask_status == 0
      
... 
