---
- name: Deploy Flask application
  hosts: webserver
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present

    - name: Clone repository
      git:
        repo: https://github.com/user/flask-app.git
        dest: /var/www/flask-app
        clone: yes
        
    - name: Install virtual environment
      command: pip3 install virtualenv
      args:
        chdir: /var/www/flask-app

    - name: Create virtual environment
      command: virtualenv venv
      args:
        chdir: /var/www/flask-app

    - name: Install requirements
      command: venv/bin/pip install -r requirements.txt
      args:
        chdir: /var/www/flask-app

    - name: Run Flask application
      command: venv/bin/gunicorn --workers 4 --bind 0.0.0.0:8000 run:app
      args:
        chdir: /var/www/flask-app
        creates: /var/run/flask-app.pid
        register: gunicorn
      notify:
        - restart gunicorn

  handlers:
    - name: restart gunicorn
      service:
        name: gunicorn
        state: restarted
        enabled: yes
  vars:
    packages:
      - git
      - python3
      - python3-pip
      - gunicorn
      
... 
